import type { CalendarEvent, EmailMessage } from "./types";

export const demoDate = "2026-04-16";

export const demoEmails: EmailMessage[] = [
  {
    id: "email-board",
    from: "Maya Chen",
    senderEmail: "maya@boardops.example.com",
    role: "Board operations",
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80",
    subject: "Board packet edits before tomorrow morning",
    preview:
      "Can you update the customer retention slide and send the final packet before 10 AM tomorrow?",
    receivedAt: "2026-04-16T07:42:00-07:00",
    priority: "urgent",
    confidence: 94,
    effort: 45,
    impact: 10,
    dueAt: "2026-04-17T10:00:00-07:00",
    category: "send",
    actionHint: "Update retention slide and send the final board packet",
    risk: "Board packet goes out with stale retention numbers.",
    labels: ["board", "deadline", "send"],
  },
  {
    id: "email-vendor",
    from: "Noah Patel",
    senderEmail: "noah@finance.example.com",
    role: "Finance",
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80",
    subject: "Approval needed: analytics renewal",
    preview:
      "Renewal discount expires today. Please approve the $18k analytics renewal or tell me to pause.",
    receivedAt: "2026-04-16T08:16:00-07:00",
    priority: "urgent",
    confidence: 91,
    effort: 15,
    impact: 8,
    dueAt: "2026-04-16T17:00:00-07:00",
    category: "approve",
    actionHint: "Approve or decline the analytics renewal",
    risk: "Discount expires and finance loses the renewal window.",
    labels: ["finance", "approval"],
  },
  {
    id: "email-candidate",
    from: "Ari Lopez",
    senderEmail: "ari@talent.example.com",
    role: "Recruiting",
    avatar:
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=160&q=80",
    subject: "Can we schedule the staff engineer loop?",
    preview:
      "The candidate can do Friday afternoon or Monday morning. Which block should I offer?",
    receivedAt: "2026-04-16T09:03:00-07:00",
    priority: "high",
    confidence: 86,
    effort: 10,
    impact: 7,
    dueAt: "2026-04-16T15:00:00-07:00",
    category: "schedule",
    actionHint: "Pick an interview block for the staff engineer candidate",
    risk: "Candidate momentum slows and the loop slips into next week.",
    labels: ["hiring", "calendar"],
  },
  {
    id: "email-launch",
    from: "Sam Rivera",
    senderEmail: "sam@product.example.com",
    role: "Product",
    avatar:
      "https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=160&q=80",
    subject: "Launch note needs your final line edit",
    preview:
      "I marked two sentences where the tone feels too cautious. Can you make the call before the 2 PM review?",
    receivedAt: "2026-04-16T09:37:00-07:00",
    priority: "high",
    confidence: 88,
    effort: 20,
    impact: 7,
    dueAt: "2026-04-16T14:00:00-07:00",
    category: "review",
    actionHint: "Make final edits to the launch note",
    risk: "Launch review starts with unclear positioning.",
    labels: ["launch", "review"],
  },
  {
    id: "email-customer",
    from: "Priya Shah",
    senderEmail: "priya@northstarhealth.com",
    role: "Customer success",
    avatar:
      "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=160&q=80",
    subject: "Escalation from Northstar Health",
    preview:
      "They want a direct reply on the missing audit export. Support can draft, but they asked for your note.",
    receivedAt: "2026-04-16T10:11:00-07:00",
    priority: "urgent",
    confidence: 90,
    effort: 25,
    impact: 9,
    dueAt: "2026-04-16T16:00:00-07:00",
    category: "reply",
    actionHint: "Send a direct reply to Northstar Health",
    risk: "High-value customer feels ignored on an audit issue.",
    labels: ["customer", "reply"],
  },
  {
    id: "email-legal",
    from: "Daniel Kim",
    senderEmail: "daniel@legal.example.com",
    role: "Legal",
    avatar:
      "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?auto=format&fit=crop&w=160&q=80",
    subject: "DPA comments are back",
    preview:
      "Vendor counsel sent comments. I need your answer on data retention before I can respond.",
    receivedAt: "2026-04-16T11:24:00-07:00",
    priority: "medium",
    confidence: 83,
    effort: 30,
    impact: 6,
    dueAt: "2026-04-17T12:00:00-07:00",
    category: "reply",
    actionHint: "Answer legal on the data retention position",
    risk: "Contract review stalls on a policy question.",
    labels: ["legal", "privacy"],
  },
  {
    id: "email-design",
    from: "Lena Brooks",
    role: "Design",
    avatar:
      "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=160&q=80",
    subject: "Homepage visuals ready for async review",
    preview:
      "No rush, but a decision this week helps us avoid another revision loop.",
    receivedAt: "2026-04-16T12:09:00-07:00",
    priority: "medium",
    confidence: 72,
    effort: 25,
    impact: 5,
    dueAt: "2026-04-18T17:00:00-07:00",
    category: "review",
    actionHint: "Review homepage visual direction",
    risk: "Design cycle keeps drifting without a decision.",
    labels: ["design", "review"],
  },
  {
    id: "email-waiting",
    from: "Victor Hall",
    role: "Engineering",
    avatar:
      "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&w=160&q=80",
    subject: "Waiting on staging logs",
    preview:
      "I will send the staging logs once the deploy finishes. Nothing for you until that lands.",
    receivedAt: "2026-04-16T12:40:00-07:00",
    priority: "low",
    confidence: 78,
    effort: 5,
    impact: 3,
    category: "follow-up",
    actionHint: "Wait for staging logs before deciding",
    risk: "No immediate risk. Keep visible so it does not vanish.",
    labels: ["engineering", "waiting"],
    waitingOn: "Victor",
  },
];

export const demoCalendar: CalendarEvent[] = [
  {
    id: "event-standup",
    title: "Team standup",
    start: "2026-04-16T09:30:00-07:00",
    end: "2026-04-16T09:55:00-07:00",
    type: "meeting",
    attendees: ["Product", "Engineering"],
  },
  {
    id: "event-investor",
    title: "Investor prep",
    start: "2026-04-16T11:00:00-07:00",
    end: "2026-04-16T11:45:00-07:00",
    type: "meeting",
    attendees: ["Maya Chen"],
  },
  {
    id: "event-review",
    title: "Launch review",
    start: "2026-04-16T14:00:00-07:00",
    end: "2026-04-16T14:45:00-07:00",
    type: "meeting",
    attendees: ["Product", "Design", "Comms"],
  },
  {
    id: "event-focus",
    title: "Protected focus",
    start: "2026-04-16T15:00:00-07:00",
    end: "2026-04-16T16:15:00-07:00",
    type: "focus",
  },
  {
    id: "event-family",
    title: "School pickup",
    start: "2026-04-16T17:30:00-07:00",
    end: "2026-04-16T18:00:00-07:00",
    type: "personal",
  },
];
