import { describe, expect, it } from "vitest";
import {
  capabilityOrder,
  filterImprovements,
  improvementIdeas,
  summarizeImprovements,
  themeLabels,
} from "./improvements";

describe("idea improver implementation registry", () => {
  it("tracks both 75-idea runs as implemented records", () => {
    expect(improvementIdeas).toHaveLength(150);
    expect(improvementIdeas.every((idea) => idea.status === "implemented")).toBe(true);
    expect(improvementIdeas.filter((idea) => idea.round === 1)).toHaveLength(75);
    expect(improvementIdeas.filter((idea) => idea.round === 2)).toHaveLength(75);
  });

  it("records AI saturation when the second pass repeats the first pass", () => {
    const summary = summarizeImprovements();

    expect(summary.total).toBe(150);
    expect(summary.implementedCount).toBe(150);
    expect(summary.uniqueTitleCount).toBe(75);
    expect(summary.duplicateRoundTwoCount).toBe(75);
    expect(summary.saturationPercent).toBe(100);
  });

  it("covers every product surface and capability family generated by the agent", () => {
    const summary = summarizeImprovements();

    for (const capability of capabilityOrder) {
      expect(summary.byCapability[capability]).toBeGreaterThan(0);
    }

    for (const theme of Object.keys(themeLabels)) {
      expect(summary.byTheme[theme as keyof typeof themeLabels]).toBeGreaterThan(0);
    }
  });

  it("filters by capability and round without losing source traceability", () => {
    const roundTwoRecommendations = filterImprovements(
      improvementIdeas,
      "recommendation",
      "round-2",
    );

    expect(roundTwoRecommendations.length).toBeGreaterThan(0);
    expect(roundTwoRecommendations.every((idea) => idea.id.startsWith("R2-"))).toBe(true);
    expect(roundTwoRecommendations.every((idea) => idea.capability === "recommendation")).toBe(
      true,
    );
  });
});
